### ISSUE TITLE
Python 3.x support?

### ISSUE THREAD

**Issue by FaceCrap** [UniverseDevel/RPA-Explorer#2]
I can point it to a Python 3.x install without issues, using the `Define Python 2.7 location` from the Option menu. 

But when I tried previewing an .rpyc file, it produced this

![image](https://github.com/UniverseDevel/RPA-Explorer/assets/95778718/5f6432f3-5f52-4507-bfe0-cff394740d39)

**Comment by UniverseDevel** [comment]
[unrpyc](https://github.com/CensoredUsername/unrpyc) does not support Python 3 to my knowledge so pointing to Python 3 will result in errors only.

**Comment by FaceCrap** [comment]
You're wrong there, It does  infact support Python 3.xxx
See maddeddy's [repo](https://github.com/madeddy/unrpyc/tree/py3_v1.1.8)

**Comment by UniverseDevel** [comment]
Thast a forked repo. I have no idea if that works and how. It was for sure not tested with this software as even readme links the one that I provided. And that one does not support Python 3 yet.

**Comment by FaceCrap** [comment]
Of course it works, I use it in my own rpa extractor/rpyc decompiler tool. 
Otherwise I wouldn't have linked to it. Just because it's a fork doesn't mean it's different, it actually has the fixes for 7.5/8.x

**Comment by UniverseDevel** [comment]
And just because it is a fork does not mean it works the same. As I said... I havn't tested it and therefore it can fail.

**Comment by UniverseDevel** [comment]
![](https://user-images.githubusercontent.com/95778718/280532941-5f6432f3-5f52-4507-bfe0-cff394740d39.png)
regarding this image, I can reproduce an problem with unrenpy and Python 2.7 as well. It seems to be a bug in my tool with using incorrect  pathing.

**Comment by UniverseDevel** [comment]
Due to this improper path while error handling it hid the real error within unrpyc. So if you are getting this error, it means unrpyc failed with error but during handling this error another error was caused. I will be publishing a fix soon.

**Comment by UniverseDevel** [comment]
https://github.com/UniverseDevel/RPA-Explorer/commit/5bb8f49afebf5381476bd4bc0153cc4c0764c3d5 should fix this bug and you should see unrpyc error properly now.

**Comment by UniverseDevel** [comment]
I have found time downloaded maddeddy's version of unrenpy, installed Python 3 and it worked as well. So I guess it should work.
